### ISSUE TITLE
Remove references to Mapbox

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-plugins-android#13]
- [ ] Remove or replace all references to Mapbox in the documentation of the repository (including the logo).
- [ ] Rename all plugins to use a maplibre resource identifier.
- [ ] Update `CONTRIBUTING.md`, remove things that are not relevant anymore going forward.
- [ ] Add a call to maintainers to the `README.md` and add a warning that each plugin (except Annotations) that it is unmaintained.

After this is done we can make a release.

**Comment by wipfli** [comment]
Can you add a link to the Bounty Direction tracking issue in maplibre/maplibre?

**Comment by louwers** [comment]
This ticket now has a small bounty in the documentation bounty direction: [#191](https://github.com/maplibre/maplibre/issues/191).

**Comment by louwers** [comment]
@wipfli I had some contact with @tempranova on Slack before assigning them, but for the next bounty I'll make sure we have the discussion on the issue so that it is public.

**Comment by wipfli** [comment]
Ah cool, as long as you talk everything is fine!

**Comment by nyurik** [comment]
Is this issue ready to be closed?  @tempranova has applied to the bounties, but I need to ensure the owner of the issue can close it before the money is distributed. Thank you Victor for working on this!!

**Comment by louwers** [comment]
@nyurik Another PR broke CI, which I want to fix first before merging. Since the scope of this bounty was documentation I think it is fair to distribute the money already (even if there turn out to be build problems).

So I am closing this ticket pending the merge.

**Comment by wipfli** [comment]
I have seen that other projects on OpenCollective get random expenses by people who never worked for a project. I think people could easily scam us by using a similar username on opencollective as some real person and then claim a bounty.

To make sure that we don't pay bounties out to the wrong people, I suggest that the person who finished a bounty adds a link to the OpenCollective expense in the GitHub ticket. And then a maintainer confirms in the GitHub ticket that the bounty was completed and the money can be paid out.

I expect that there will be quite some payments for bounties coming together in the next months. To streamline thing a bit I suggest that people can submit bounty expenses up to the 15th of the month, and then we pay the bounties out on the 16th. If someone files an expense after the 15th of the month, they get paid in the next month's 16th.

On every 16th of the month, one person from the team or the Governing Board should do all the payments. Like that we can keep an overview more easily.

I will write that down more clearly in a wiki entry but let's do it like that for now.

cc @louwers @ovivoda @HarelM @nyurik @birkskyum

**Comment by HarelM** [comment]
Sounds good to me.

**Comment by louwers** [comment]
Alright! ✅
