### ISSUE TITLE
Archive maplibre-plugins-android

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-plugins-android#2]
@petr-pokorny-1, this repo seems to be inactive. Can we archive it?

**Comment by matkoniecz** [comment]
https://github.com/maplibre/maplibre-plugins-android#installing-a-plugin - are this plugins published by maplibre somewhere? Or is it a dead repo?

**Comment by louwers** [comment]
@wipfli Mapbox deprecated Annotations and made this plugin the prefered way to add them.

If we deprecate this depository, we should undeprecate Annotations in the Android SDK.

**Comment by louwers** [comment]
We have decided to keep the Annotations plugin in favor the Annotations functionality part of the core: https://github.com/maplibre/maplibre/pull/206

The other plugins in this repository now have 'Hosted' status.
