### ISSUE TITLE
Update dependencies to make the project build again

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-plugins-android#20]
A lot of things including Gradle (the wrapper), Android Gradle Plugin and Kotlin Gradle Plugin are three years out of days. I am having a lot of build problems because of that. `kotlin-android-extensions` is also deprecated: https://developer.android.com/topic/libraries/view-binding/migration

**Comment by louwers** [comment]
I started looking into this, but ran into a problem: https://github.com/maplibre/maplibre-plugins-android/pull/21

**Comment by abebeos** [comment]
@louwers , it looks like this can be closed.
