### ISSUE TITLE
Update for MapLibre Native Android 11.0.0

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-plugins-android#49]
[MapLibre Native Android 11.0.0](https://github.com/maplibre/maplibre-native/releases/tag/android-v11.0.0-pre0) has different import paths. Does anyone volunteer to update this package?

**Comment by kocheick** [comment]
I'm working on it ... please the current changes made

**Comment by kocheick** [comment]
Sent a PR for review regarding the update of packages here :
 https://github.com/maplibre/maplibre-plugins-android/pull/52

Please, advise.

**Comment by louwers** [comment]
Done!
