### ISSUE TITLE
Maplibre plugins without Mapbox?

### ISSUE THREAD

**Issue by EULUSOY** [maplibre/maplibre-plugins-android#51]
Can I use Maplibre plugins without Mapbox credentials?

I want to use basic marker, scale map features. Is there a way to use without mapbox?

**Comment by louwers** [comment]
Hi please use Discussions on the main repo for questions: https://github.com/maplibre/maplibre-native/discussions

If you want a base map you need to use a tile provider such as Jawg Maps.
