### ISSUE TITLE
Maplibre Android Plugin Installation V11 2.0.2

### ISSUE THREAD

**Issue by EULUSOY** [maplibre/maplibre-plugins-android#56]
Hi;
I'm trying to use plugins updated with Maplibre V11.
I tried the installations below, but I could not install the plugins. Which format is correct?

App level build.gradle:
    implementation ("org.maplibre.android:maplibre-android-plugin-annotation-v11:2.0.2")
    implementation ("org.maplibre.android:maplibre-android-plugin-scalebar-v11:2.0.2")

Project level build.gradle:
        maven {
            url = uri("https://api.mapbox.com/downloads/v2/releases/maven")
            // Do not change the username below. It should always be "mapbox" (not your username).
            credentials.username = "mapbox"
            // Use the secret token stored in gradle.properties as the password
            credentials.password = providers.gradleProperty("MAPBOX_DOWNLOADS_TOKEN").get()
            authentication.create<BasicAuthentication>("basic")
        }

**Comment by louwers** [comment]
They are not released yet.

**Comment by krupupakku** [comment]
Also I think next version will be:
implementation ("org.maplibre.android:maplibre-android-plugin-annotation-v11:3.0.0")
or something like this :P

**Comment by louwers** [comment]
Good point. We didn't update the package name for v10. Maybe we should drop the version postfix altogether?

**Comment by louwers** [comment]
@krupupakku Created an issue here: https://github.com/maplibre/maplibre-plugins-android/issues/new

**Comment by mavol24** [comment]
nice thanks!
