### ISSUE TITLE
Symbol Titles Not Working With Raster Map Source (Android SDK)

### ISSUE THREAD

**Issue by EllisGlaeser** [maplibre/maplibre-plugins-android#61]
Does the textField only work when you're using vector maps? Every time I try to use text for a symbol, the symbol disappears. If I use a default map like in the Maplibre demo app, it works fine.

In this example, the symbol only shows if you comment out the line to add the map source, even if you aren't using a text field on the symbol, but I'm assuming they are related.

I am using the latest Maplibre and annotation plugin versions.

```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        MapLibre.getInstance(this)

        mapView = MapView(this)

        setContent {
            loadMap(mapView)
            MapLibreSymbolsExampleTheme {
                AndroidView(
                    {
                        mapView
                    }
                )
            }
        }
    }

    private fun loadMap(mapView: MapView) {
        mapView.getMapAsync { map ->
            map.setStyle(Style.Builder()) { style ->
                val sourceURL = "https://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer/tile/{z}/{y}/{x}"
                val source = RasterSource("usNat", TileSet("3.0.0", sourceURL))
                val sourceID = "usNat"

                val coordinate = LatLng(48.11166, 121.11486)

                val symbolManager = SymbolManager(mapView, map, style)
                val imgName = "Point"
                val bmp = BitmapFactory.decodeResource(this@MainActivity.resources, R.drawable.markerbrown)

                // Once you add the source, you can't see the image.
//                style.addSource(source)
                style.addLayer(RasterLayer("map-layer", sourceID))
                style.addImage(imgName, bmp)

                symbolManager.create(
                    SymbolOptions()
                        .withLatLng(coordinate)
                        .withIconImage(imgName)
                        .withIconSize(1f)
                        .withSymbolSortKey(1f)
                        // If you take out the text field, the marker appears.
//                        .withTextField(imgName)
                )

                map.cameraPosition = CameraPosition.Builder().target(coordinate).zoom(10.0).build()
            }
        }
    }
```

**Comment by louwers** [comment]
@EllisGlaeser Did you manage to find the problem?

**Comment by EllisGlaeser** [comment]
@louwers Yes, it looks like the problem is that I wasn't using a style.json file with a glyphs entry. My question is why doesn't the default style builder handle that? 

Adding a style json with the map sources also fixed a crash I had where if the app reopened from the back stack (e.g. receiving a shared GPX file from another app), it would crash upon re-initializing the map. I had been adding all my sources through `style.addSource()`, and it would crash upon trying to add the first source, saying the source already existed. When I would look at it in the debugger, the sources were empty, and I tried removing the source first but it would still crash. Is that just not the intended way of adding sources?

Now I am trying to figure out how to refactor our code for updating the map (we have a lot of options for maps & overlays), as well as for caching and downloading tiles, since we had been doing that on an internal server. Is there a way to handle these in MapLibre? We package downloads together so the user can see what maps & overlays were in the download and add to it or delete from it.
