### ISSUE TITLE
Android R8 minimize fails with android-v11.2.0

### ISSUE THREAD

**Issue by ganfra** [maplibre/maplibre-plugins-android#64]
**Describe the bug**
R8 Minimize fails with the latest version https://github.com/maplibre/maplibre-native/releases/tag/android-v11.2.0
Downgrading to version `11.1.0 ` works. 

I guess it comes from https://github.com/maplibre/maplibre-native/pull/2714

See the logs : 
`AGPBI: {"kind":"error","text":"Missing class com.mapbox.android.gestures.AndroidGesturesManager (referenced from: com.mapbox.android.gestures.AndroidGesturesManager org.maplibre.android.plugins.annotation.DraggableAnnotationController$1.val$androidGesturesManager and 4 other contexts)\nMissing class com.mapbox.android.gestures.MoveGestureDetector$OnMoveGestureListener (referenced from: void org.maplibre.android.plugins.annotation.DraggableAnnotationController.<init>(org.maplibre.android.maps.MapView, org.maplibre.android.maps.MapLibreMap, com.mapbox.android.gestures.AndroidGesturesManager, int, int, int, int) and 1 other context)","sources":[{}],"tool":"R8"}`

**Comment by ganfra** [comment]
Ok, importing `com.mapbox.mapboxsdk:mapbox-android-gestures:0.7.0` fixes the issue.
I guess it should still be managed by the plugin?

**Comment by louwers** [comment]
We need to update the plugin and make a new release.

**Comment by louwers** [comment]
I just published a new version of the annotations plugin (3.0.1-pre1).

Could anyone try it out?

https://central.sonatype.com/artifact/org.maplibre.gl/android-plugin-annotation-v9/versions

**Comment by louwers** [comment]
3.0.1 has been released. Please let me know if there are any problems.

**Comment by ganfra** [comment]
Sorry I hadn't seen the update. Working properly, thanks!
